
pipeline {
    agent none
    stages {
        stage('unittest') {
            agent {
                docker {
                    image 'snirben/atlas:atlasv1'
                }
            }
            steps {
                sh 'python manage.py test'
            }
            post {
                always {
                    junit 'test-reports/results.xml'
                }
            }
        }
    }

