
pipeline {
    agent {
        docker {
                    image 'snirben/atlas:atlasv3'
                }}
    stages {
        stage('Build'){
        steps{
        sh 'git-force-clone clone https://github.com/snirben/Atlas.git'
        sh 'sudo pip3 install -r requirements.txt'
        }
        }
        stage('Unit-Test') {
            steps {
                sh 'python3 manage.py makemigrations'
                sh 'python3 manage.py migrate'
                sh 'python3 manage.py test'
            }
            post {
                always {
                    junit 'test-reports/junit.xml'
                }
            }
        }
    }
  }
